import {
  MapPin,
  Ship,
  Waves,
  Car,
  Package,
  Home,
  Hotel,
  Info,
  Camera,
  Users,
  Star,
  Palmtree,
  Mountain,
  Briefcase,
  Heart,
  Zap,
} from "lucide-react";

export const companyConfig = {
  name: "DD Tours & Travels",
  founderImg: "founder.jpg",
  logo: "logo.jpg",
  contact: {
    phone: "+91 9626850192",
    whatsapp: "919626850192", // International format for URL linking
    email: "info@maheshtours.com", // Added missing data
  },
  address: {
    street: "133/Chellandiamman Kovil Street",
    city: "Valparai",
    state: "Tamil Nadu",
    pincode: "642127",
    country: "India",
  },
  socials: {
    facebook: "https://facebook.com/maheshtours",
    instagram: "https://instagram.com/maheshtours",
    googleMaps: "https://maps.app.goo.gl/example",
  },
  metadata: {
    foundingYear: "2000s",
    serviceAreas: ["Valparai", "Pollachi", "Kerala", "South India"],
  },
};


const tours = [
  // ─────────────────────────────────────────────
  // INTERNATIONAL TOUR PACKAGES
  // ─────────────────────────────────────────────
  {
    id: 1,
    category: "International",
    title: "Thailand Tour Package",
    duration: "4 Nights / 5 Days",
    description:
      "Enjoy the best of Thailand, from the bustling beaches of Pattaya and Coral Island to the vibrant city life and temples of Bangkok.",
    image: "/Internation/Thailand Tour Package.avif",
  },
  {
    id: 2,
    category: "International",
    title: "Bali Tour Package",
    duration: "4 Nights / 5 Days",
    description:
      "Explore the best of Bali with our curated 5-day tour package.",
    image: "/Internation/Bali Tour Package.jpg",
  },
  {
    id: 3,
    category: "International",
    title: "Sri Lanka Tour Package",
    duration: "4 Nights / 5 Days",
    description:
      "Explore the jewels of Sri Lanka, from the cultural city of Kandy to the scenic hills of Nuwara Eliya and the beautiful beaches of Bentota.",
    image: "/Internation/Sri Lanka Tour Package.jpg",
  },
  {
    id: 4,
    category: "International",
    title: "Singapore Tour Package",
    duration: "3 Nights / 4 Days",
    description:
      "Discover the vibrant city-state of Singapore, from the thrilling Night Safari and Universal Studios to the stunning views from Sentosa Island.",
    image: "/Internation/Singapore Tour Package.jpg",
  },
  {
    id: 5,
    category: "International",
    title: "Vietnam Tour Package",
    duration: "4 Nights / 5 Days",
    description:
      "Experience the dynamic energy of Ho Chi Minh City, explore the historic Cu Chi Tunnels, and cruise through the lush Mekong Delta.",
    image: "/Internation/Vietnam Tour Package.jpg",
  },
  {
    id: 6,
    category: "International",
    title: "Dubai Tour Package",
    duration: "4 Nights / 5 Days",
    description:
      "Experience the glamour of Dubai with a Dhow Cruise, a desert safari, a visit to the Burj Khalifa, and exploring the Miracle Garden.",
    image: "/Internation/Dubai Tour Package.jpg",
  },
  {
    id: 7,
    category: "International",
    title: "Malaysia Tour Package",
    duration: "3 Nights / 4 Days",
    description:
      "Explore the vibrant Kuala Lumpur, ascend to the cool Genting Highlands, and visit the iconic Batu Caves on this Malaysian adventure.",
    image: "/Internation/Malaysia-Tour-Package.jpg",
  },
  {
    id: 8,
    category: "International",
    title: "China Tour Package",
    duration: "7 Nights / 8 Days",
    description: "China Awaits — Beyond Every Horizon.",
    image: "/Internation/china-tour-package-from-india.jpg",
  },
  {
    id: 9,
    category: "International",
    title: "European Highlights Tour Package",
    duration: "10 Nights / 11 Days",
    description: "Paris to Rome – A Journey Through Timeless Beauty.",
    image: "/Internation/European Highlights Tour Package.webp",
  },
  {
    id: 10,
    category: "International",
    title: "Malaysia and Singapore Tour Package",
    duration: "5 Nights / 6 Days",
    description: "Skyline to Islands – Explore Singapore & Malaysia.",
    image: "/Internation/Singapore-Malaysia-Tour-Package.jpg",
  },
  {
    id: 11,
    category: "International",
    title: "Beauty of Europe Tour Package (Paris, Amsterdam, Switzerland)",
    duration: "9 Nights / 10 Days",
    description:
      "Experience the Magic of Europe – Culture, Cuisine and Scenic Wonders!",
    image: "/Internation/Beauty of Europe Tour Package (Paris, Amsterdam, Switzerland).jpg",
  },
  {
    id: 12,
    category: "International",
    title: "Jewels of East Europe Tour Package",
    duration: "7 Nights / 8 Days",
    description: "A Grand Escape Through Europe's Historic Heart.",
    image: "/Internation/Jewels of East Europe Tour Package.jpg",
  },
  {
    id: 13,
    category: "International",
    title: "Switzerland Tour Package",
    duration: "7 Nights / 8 Days",
    description: "From City Lights to Snowy Heights – The Ultimate Swiss Escape.",
    image: "/Internation/best-of-switzerland.jpg",
  },
  {
    id: 14,
    category: "International",
    title: "Scandinavia Tour Package",
    duration: "9 Nights / 10 Days",
    description: "Scandinavian Dreams: Where Nature Meets Nordic Elegance.",
    image: "/Internation/Scandinavia Tour Package.webp",
  },
  {
    id: 15,
    category: "International",
    title: "Hawaii Tour Package",
    duration: "9 Nights / 10 Days",
    description: "Hawaii Awaits – Paradise Beyond Imagination.",
    image: "/Internation/Hawaii Tour Package.avif",
  },
  {
    id: 16,
    category: "International",
    title: "Elegant East Canada Tour Package",
    duration: "7 Nights / 8 Days",
    description: "Elegant East Canada – Where Nature Meets Timeless Charm.",
    image: "/Internation/Elegant-East-Canada-Tour-Package-3.webp",
  },
  {
    id: 17,
    category: "International",
    title: "New Zealand Tour Package",
    duration: "9 Nights / 10 Days",
    description: "Experience Paradise: 10 Days Across New Zealand's Wonders.",
    image: "/Internation/New Zealand Tour Package.jpg",
  },
  {
    id: 18,
    category: "International",
    title: "Bhutan Tour Package",
    duration: "3 Nights / 4 Days",
    description: "From Paro to Punakha – A Journey Through Peace & Beauty.",
    image: "/Internation/bhutan.webp",
  },
  {
    id: 19,
    category: "International",
    title: "Kathmandu Pokhara Tour Package",
    duration: "5 Nights / 6 Days",
    description: "Explore. Experience. Elevate – Nepal Calling!",
    image: "/Internation/Kathmandu Pokhara Tour Package.jpg",
  },
  {
    id: 20,
    category: "International",
    title: "Reunion Island Tour Package",
    duration: "3 Nights / 4 Days",
    description: "Reunion Island – Adventure in the Heart of the Indian Ocean.",
    image: "/Internation/Reunion Island Tour Package.jpg",
  },
  {
    id: 21,
    category: "International",
    title: "Australia and New Zealand Tour Package",
    duration: "15 Nights / 16 Days",
    description: "From Sydney's Skyline to New Zealand's Scenic Paradise.",
    image: "/Internation/Australia and New Zealand Tour Package.jpg.webp",
  },
  {
    id: 22,
    category: "International",
    title: "Philippines (Manila and El Nido) Tour Package",
    duration: "4 Nights / 5 Days",
    description:
      "From Manila's Heritage Streets to El Nido's Paradise Beaches – Discover the Best of the Philippines.",
    image: "/Internation/Philippines (Manila and El Nido) Tour Package.jpg",
  },
  {
    id: 23,
    category: "International",
    title: "Philippines (Manila, Angeles) Tour Package",
    duration: "4 Nights / 5 Days",
    description: "Your Perfect Philippine Twin-City Escape – Manila & Angeles.",
    image: "/Internation/Philippines (Manila, Angeles) Tour Package.jpg",
  },
  {
    id: 24,
    category: "International",
    title: "Philippines (Manila, El Nido, Puerto Princesa) Tour Package",
    duration: "6 Nights / 7 Days",
    description: "Heritage Streets, Turquoise Lagoons & Underground Wonders.",
    image: "/Internation/Philippines (Manila, El Nido, Puerto Princesa) Tour Package.webp",
  },
  {
    id: 25,
    category: "International",
    title: "Philippines (Manila) Tour Package",
    duration: "3 Nights / 4 Days",
    description:
      "From Heritage Streets to Volcanic Peaks – Experience the Best of Manila.",
    image: "/Internation/Philippines (Manila) Tour Package.webp",
  },
  {
    id: 26,
    category: "International",
    title: "Philippines (Manila, Boracay, Cebu) Tour Package",
    duration: "6 Nights / 7 Days",
    description:
      "City Lights, Island Vibes, Ocean Adventures – Discover the Philippines!",
    image: "/Internation/Philippines (Manila, Boracay, Cebu) Tour Package.jpg",
  },
  {
    id: 27,
    category: "International",
    title: "Australia Tour Package",
    duration: "9 Nights / 10 Days",
    description:
      "From the Great Ocean Road to the Great Barrier Reef – Pure Australian Magic.",
    image: "/Internation/Australia Tour Package.jpg.webp",
  },
  {
    id: 28,
    category: "International",
    title: "Hong Kong – Macau Tour Package",
    duration: "5 Nights / 6 Days",
    description:
      "Where Skyline Meets Heritage – Discover Hong Kong & Macau in Style.",
    image: "/Internation/hong-kong-macau-tour-package-service.jpg",
  },
  {
    id: 29,
    category: "International",
    title: "Canada Tour Package",
    duration: "14 Nights / 15 Days",
    description:
      "From Thundering Falls to Majestic Rockies – Experience the Best of Canada in One Grand Journey.",
    image: "/Internation/Canada Tour Package.webp",
  },
  {
    id: 30,
    category: "International",
    title: "Orlando Theme Park Extravaganza Tour Package",
    duration: "4 Nights / 5 Days",
    description: "Experience the Magic, Adventure & Marine Wonders of Orlando!",
    image: "/Internation/Orlando Theme Park Extravaganza Tour Package.webp",
  },
  {
    id: 31,
    category: "International",
    title: "Iceland Tour Package",
    duration: "8 Nights / 9 Days",
    description:
      "Chase Glaciers, Waterfalls & Northern Wonders – Discover Iceland in a Complete Circle!",
    image: "/Internation/iceland-northen-lights.jpg",
  },
  {
    id: 32,
    category: "International",
    title: "Texas Tour Package",
    duration: "6 Nights / 7 Days",
    description:
      "Discover the Spirit of Texas – From Space Exploration to Historic Trails, Live Music & Iconic Dallas!",
    image: "/Internation/Texas Tour Package.avif",
  },
  {
    id: 33,
    category: "International",
    title: "Canada Eastern Delight Tour Package",
    duration: "7 Nights / 6 Days",
    description:
      "Experience the Best of Eastern Canada – From Niagara Falls to the Historic Charm of Montreal & Quebec City!",
    image: "/Internation/Canada Eastern Delight Tour Package.webp",
  },
  {
    id: 34,
    category: "International",
    title: "Morocco Tour Package",
    duration: "12 Nights / 13 Days",
    description:
      "Morocco Unveiled – Imperial Cities, Sahara Nights & Coastal Charm.",
    image: "/Internation/Morocco-Eco-Tourism-Tour-Package-2.webp",
  },
  {
    id: 35,
    category: "International",
    title: "Hong Kong and Macau Tour Package",
    duration: "5 Nights / 6 Days",
    description:
      "Hong Kong & Macau – A Perfect Blend of Modern Marvels and Classic Charm.",
    image: "/Internation/Hong Kong and Macau Tour Package.jpg.webp",
  },
  {
    id: 36,
    category: "International",
    title: "Cambodia and Vietnam Tour Package",
    duration: "6 Nights / 7 Days",
    description:
      "Ancient Temples to Vibrant Cities – Explore Cambodia & Vietnam.",
    image: "/Internation/Cambodia and Vietnam Tour Package.jpg.webp",
  },
  {
    id: 37,
    category: "International",
    title: "Europe (Zurich – Paris – Amsterdam) Tour Package",
    duration: "8 Nights / 9 Days",
    description: "Europe Beyond Borders, Beyond Expectations.",
    image: "/Internation/Europe (Zurich – Paris – Amsterdam) Tour Package.jpg.webp",
  },
  {
    id: 38,
    category: "International",
    title: "Brunei and Malaysia Tour Package",
    duration: "5 Nights / 6 Days",
    description: "Brunei & Malaysia – A Perfect Blend of Heritage and Skyline.",
    image: "/Internation/Brunei and Malaysia Tour Package.jpg",
  },
  {
    id: 39,
    category: "International",
    title: "Eastern Europe Tour Package",
    duration: "5 Nights / 6 Days",
    description: "Discover the Timeless Charm of East Europe.",
    image: "/Internation/Eastern Europe Tour Package.jpg",
  },
  {
    id: 40,
    category: "International",
    title: "Phuket and Krabi Tour Package",
    duration: "4 Nights / 5 Days",
    description: "Phuket & Krabi – Thailand's Twin Treasures of Paradise.",
    image: "/Internation/Phuket and Krabi Tour Package.avif",
  },
  {
    id: 41,
    category: "International",
    title: "Kathmandu with Chandagiri Hills Tour Package",
    duration: "3 Nights / 4 Days",
    description: "Kathmandu – Where Culture Touches the Clouds.",
    image: "/Internation/Kathmandu with Chandagiri Hills Tour Package.webp",
  },
  {
    id: 42,
    category: "International",
    title: "Cairo + Aswan & Luxor Nile Cruise",
    duration: "6 Nights / 7 Days",
    description: "Explore Ancient Egypt, Sail the Legendary Nile.",
    image: "/Internation/Cairo + Aswan & Luxor Nile Cruise.jpg",
  },
  {
    id: 43,
    category: "International",
    title: "Penang Tour Package",
    duration: "3 Nights / 4 Days",
    description:
      "Experience Penang's vibrant heritage, iconic landmarks, and unforgettable views.",
    image: "/Internation/Penang Tour Package.jpg",
  },
  {
    id: 44,
    category: "International",
    title: "Langkawi Tour Package",
    duration: "3 Nights / 4 Days",
    description:
      "Escape to Langkawi and enjoy breathtaking views, island hopping, cable car thrills, and serene sunsets.",
    image: "/Internation/Langkawi-tour-package.jpg",
  },
  {
    id: 45,
    category: "International",
    title: "Azerbaijan Tour Package",
    duration: "4 Nights / 5 Days",
    description: "Azerbaijan – Where Ancient History Meets Modern Skylines.",
    image: "/Internation/Azerbaijan Tour Package.jpg",
  },
  {
    id: 46,
    category: "International",
    title: "Phu Quoc and Da Nang Tour Package",
    duration: "5 Nights / 6 Days",
    description: "Phu Quoc & Da Nang – Beach to Mountains.",
    image: "/Internation/Phu Quoc and Da Nang Tour Package.webp",
  },
  {
    id: 47,
    category: "International",
    title: "Phu Quoc Tour Package",
    duration: "3 Nights / 4 Days",
    description: "Phu Quoc – Vietnam's Island Paradise.",
    image: "/Internation/Phu Quoc Tour Package.jpg",
  },
  {
    id: 48,
    category: "International",
    title: "Kazakhstan Tour Package",
    duration: "4 Nights / 5 Days",
    description: "Experience the True Spirit of Kazakhstan.",
    image: "/Internation/kazakhstan-holiday-packages-from-india.jpg",
  },
  {
    id: 49,
    category: "International",
    title: "Europe Tour Package",
    duration: "13 Nights / 14 Days",
    description:
      "Walk Through Centuries of Wonders – Travel Europe the Grand Way.",
    image: "/Internation/Europe-Tour-Package-from-India.jpg",
  },
  {
    id: 50,
    category: "International",
    title: "Japan Tour Package",
    duration: "7 Nights / 8 Days",
    description:
      "From Bullet Trains to Bamboo Forests – Experience Japan in Every Dimension.",
    image: "/Internation/japan.jpg",
  },
  {
    id: 51,
    category: "International",
    title: "Mauritius Tour Package",
    duration: "4 Nights / 5 Days",
    description: "Mauritius — A World of Wonders on One Island.",
    image: "/Internation/Mauritius-Tour-Package-with-Flight.jpg",
  },
  {
    id: 52,
    category: "International",
    title: "Turkey – Istanbul, Cappadocia, Kusadasi Tour Package",
    duration: "8 Nights / 9 Days",
    description: "Connect, Inspire, Discover Turkey.",
    image: "/Internation/Turkey – Istanbul, Cappadocia, Kusadasi Tour Package.webp",
  },
  {
    id: 53,
    category: "International",
    title: "Turkey – Istanbul Tour Package",
    duration: "4 Nights / 5 Days",
    description: "Istanbul: East Meets Wow.",
    image: "/Internation/istanbul-tour1.jpg",
  },
  {
    id: 54,
    category: "International",
    title: "Egypt Tour Package",
    duration: "7 Nights / 8 Days",
    description: "From Pyramids to the Nile – Experience Egypt in Style.",
    image: "/Internation/Egypt Tour Package.webp",
  },
  {
    id: 55,
    category: "International",
    title: "Kenya Tour Package",
    duration: "6 Nights / 7 Days",
    description: "Kenya – Where the Wild Meets Culture and City Life.",
    image: "/Internation/Kenya Tour Package.jpg.webp",
  },
  {
    id: 56,
    category: "International",
    title: "Baku Tour Package",
    duration: "4 Nights / 5 Days",
    description: "Baku: A Modern Soul with Ancient Roots.",
    image: "/Internation/baku-azerbaijan.jpg",
  },
  {
    id: 57,
    category: "International",
    title: "Almaty with Charyn Canyon Tour Package",
    duration: "5 Nights / 6 Days",
    description:
      "From Snowy Peaks to Ancient Canyons – Experience the Best of Almaty.",
    image: "/Internation/Almaty with Charyn Canyon Tour Package.jpg",
  },
  {
    id: 58,
    category: "International",
    title: "Cambodia Tour Package",
    duration: "4 Nights / 5 Days",
    description: "Cambodia: Where History Lives and Adventure Begins.",
    image: "/Internation/cambodia-tour-packages.jpg",
  },

  // ─────────────────────────────────────────────
  // DOMESTIC TOUR PACKAGES
  // ─────────────────────────────────────────────
  {
    id: 59,
    category: "Domestic",
    title: "Mysore & Coorg Tour Package",
    duration: "3 Nights / 4 Days",
    description:
      "Discover the royal heritage of Mysore and the lush coffee plantations and misty hills of Coorg in this scenic Karnataka tour.",
    image: "/domestic/Mysore-and-Coorg-Tour-Packages-scaled.webp",
  },
  {
    id: 60,
    category: "Domestic",
    title: "Andaman Tour Package",
    duration: "4 Nights / 5 Days",
    description:
      "Explore the pristine beaches of Andaman, from the historic Cellular Jail in Port Blair to the world-famous Radhanagar Beach on Havelock Island.",
    image: "/domestic/Andaman-Honeymoon1-1.jpg",
  },
  {
    id: 61,
    category: "Domestic",
    title: "Goa Tour Package",
    duration: "3 Nights / 4 Days",
    description:
      "Experience the sun, sand, and sea of Goa with comprehensive tours of both the vibrant North and the tranquil South.",
    image: "/domestic/Goa Tour Package.webp",
  },
  {
    id: 62,
    category: "Domestic",
    title: "Golden Triangle Tour (Delhi-Agra-Jaipur)",
    duration: "5 Nights / 6 Days",
    description:
      "Embark on the classic Golden Triangle journey, discovering the historical wonders of Delhi, the iconic Taj Mahal in Agra, and the royal palaces of Jaipur.",
    image: "/domestic/Golden-triangle-tour.jpg",
  },
  {
    id: 63,
    category: "Domestic",
    title: "Darjeeling & Gangtok Tour Package",
    duration: "4 Nights / 5 Days",
    description:
      "Explore the Queen of the Hills, Darjeeling, and the pristine capital of Sikkim, Gangtok, with stunning views of the Himalayas.",
    image: "/domestic/darjeeling-gangtok-tour-package-service.jpg",
  },
  {
    id: 64,
    category: "Domestic",
    title: "Cultural Rajasthan Tour Package",
    duration: "12 Nights / 13 Days",
    description:
      "From the Golden City to the City of Love – Explore India's Finest.",
    image: "/domestic/Festivals-of-Rajasthan-min.jpg",
  },
  {
    id: 65,
    category: "Domestic",
    title: "Haridwar Rishikesh with Mussoorie Tour Package",
    duration: "4 Nights / 5 Days",
    description:
      "Pray, Explore & Unwind – Haridwar, Rishikesh & Mussoorie Awaits.",
    image: "/domestic/haridwar-rishikesh-with-mussoorie-tour.jpg",
  },
  {
    id: 66,
    category: "Domestic",
    title: "Varanasi (Bodhgaya Prayagraj Ayodhya) Tour Package",
    duration: "6 Nights / 7 Days",
    description: "Divine Path of Faith – From Ganga to Enlightenment.",
    image: "/domestic/varanasi-bodhgaya-prayagraj-with-ayodhya-tour-package.webp",
  },
  {
    id: 67,
    category: "Domestic",
    title: "Manali Tour Package",
    duration: "5 Nights / 6 Days",
    description: "Manali Escape – Where Mountains Meet Memories.",
    image: "/domestic/Manali Tour Package.jpg",
  },
  {
    id: 68,
    category: "Domestic",
    title: "Kashi Tour Package",
    duration: "4 Nights / 5 Days",
    description: "From Gaya Rituals to Ganga Aarti – A Divine Experience.",
    image: "/domestic/premium-kashi-tour-package.jpg",
  },
  {
    id: 69,
    category: "Domestic",
    title: "Blissful Amarnath Yatra Package",
    duration: "4 Nights / 3 Days",
    description:
      "Experience Faith, Devotion, and the Power of the Himalayas.",
    image: "/domestic/Blissful Amarnath Yatra Package.jpg",
  },
  {
    id: 70,
    category: "Domestic",
    title: "Muktinath Temple – Nepal Tour Package",
    duration: "6 Nights / 7 Days",
    description: "Where Faith Meets the Himalayas – Muktinath Yatra.",
    image: "/domestic/Muktinath Temple – Nepal Tour Package.webp",
  },
  {
    id: 71,
    category: "Domestic",
    title: "Mussoorie and Dhanaulti Tour Package",
    duration: "3 Nights / 4 Days",
    description:
      "Mist, Mountains & Memories – Mussoorie and Dhanaulti Getaway.",
    image: "/domestic/Mussoorie and Dhanaulti Tour Package.jpg",
  },
  {
    id: 72,
    category: "Domestic",
    title: "Mussoorie – Dhanaulti Tour Package",
    duration: "3 Nights / 4 Days",
    description:
      "Where Misty Mountains Meet Peaceful Pines – Mussoorie & Dhanaulti Awaits!",
    image: "/domestic/Mussoorie – Dhanaulti Tour Package.jpg",
  },
  {
    id: 73,
    category: "Domestic",
    title: "Golden Route (Delhi–Agra–Jaipur–Jodhpur–Udaipur) Tour Package",
    duration: "8 Nights / 9 Days",
    description: "Experience India's Golden Heritage in One Timeless Journey.",
    image: "/domestic/Golden Route (Delhi–Agra–Jaipur–Jodhpur–Udaipur) Tour Package.png",
  },
  {
    id: 74,
    category: "Domestic",
    title: "Himalayas – Shimla and Manali Tour Package",
    duration: "4 Nights / 5 Days",
    description:
      "Queen of Hills – Discover the Timeless Beauty of Shimla & Manali.",
    image: "/domestic/Shimla-Manali-Tour-Package-–-Best-Himachal-Holiday.webp",
  },
  {
    id: 75,
    category: "Domestic",
    title: "Do Dham – Kedarnath and Badrinath Tour Package",
    duration: "5 Nights / 6 Days",
    description: "Do Dham Yatra – Where Faith Meets the Himalayas.",
    image: "/domestic/Do Dham – Kedarnath and Badrinath Tour Package.jpg",
  },
  {
    id: 76,
    category: "Domestic",
    title: "Dwarka – Somnath Tour Package",
    duration: "3 Nights / 4 Days",
    description:
      "Dwarka–Somnath – Experience India's Sacred Heritage with Peace & Comfort.",
    image: "/domestic/Dwarka – Somnath Tour Package.png",
  },
  {
    id: 77,
    category: "Domestic",
    title: "Kathmandu and Lumbini Tour Package",
    duration: "7 Nights / 8 Days",
    description: "Explore Kathmandu's Heritage and Lumbini's Peace.",
    image: "/domestic/Kathmandu-Lumbini-Tour-Package.jpg",
  },
  {
    id: 78,
    category: "Domestic",
    title: "Kathmandu and Sanga Tour Package",
    duration: "3 Nights / 4 Days",
    description:
      "A soulful journey through heritage, spirituality, and Himalayan serenity.",
    image: "/domestic/Kathmandu and Sanga Tour Package.jpg",
  },
  {
    id: 79,
    category: "Domestic",
    title: "Gujarat Tour Package",
    duration: "11 Nights / 12 Days",
    description: "Experience the Culture, Colors & Heritage of Gujarat.",
    image: "/domestic/Gujarat Tour Package.jpg",
  },
  {
    id: 80,
    category: "Domestic",
    title: "Kerala Tour Package",
    duration: "5 Nights / 6 Days",
    description: "Kerala Tour Package – Serenity in Every Moment.",
    image: "/domestic/Kerala Tour Package.jpg",
  },
  {
    id: 81,
    category: "Domestic",
    title: "Do Dham Yatra Tour Package",
    duration: "7 Nights / 8 Days",
    description: "Two Holy Shrines, One Spiritual Journey.",
    image: "/domestic/Do Dham Yatra Tour Package.jpg",
  },
  {
    id: 82,
    category: "Domestic",
    title: "Char Dham Yatra Tour Package",
    duration: "8 Nights / 9 Days",
    description: "Char Dham Yatra: Where Devotion Meets the Himalayas.",
    image: "/domestic/Chardham-Yatra.webp",
  },
  {
    id: 83,
    category: "Domestic",
    title: "Rajasthan Tour Package",
    duration: "7 Nights / 8 Days",
    description: "A Journey Through Palaces, Deserts & Traditions.",
    image: "/domestic/Rajasthan-Tour-Packages-For-9-Days-8-Nights.webp",
  },
  {
    id: 84,
    category: "Domestic",
    title: "Kashmir Tour Package",
    duration: "4 Nights / 5 Days",
    description: "Kashmir – Where Every View Feels Like a Painting.",
    image: "/domestic/Kashmir Tour Package.webp",
  },
  {
    id: 85,
    category: "Domestic",
    title: "Hyderabad Tour Package",
    duration: "3 Nights / 4 Days",
    description:
      "Charminar to Chowmahalla – Experience the Royal City of Hyderabad.",
    image: "/domestic/Hydrabad-Featered.webp",
  },
  {
    id: 86,
    category: "Domestic",
    title: "Assam Tour Package",
    duration: "4 Nights / 5 Days",
    description: "Assam: Untouched, Unexplored, Unforgettable.",
    image: "/domestic/assam-meghalaya-tour-package-from-Chennai.jpg",
  },
  {
    id: 87,
    category: "Domestic",
    title: "Shimla / Manali Tour Package",
    duration: "5 Nights / 6 Days",
    description: "Experience the Timeless Beauty of Shimla & Manali.",
    image: "/domestic/shimla-manali-tours.webp",
  },
  {
    id: 88,
    category: "Domestic",
    title: "Srinagar Tour Package",
    duration: "5 Nights / 6 Days",
    description: "Srinagar – Paradise on Earth Awaits You.",
    image: "/domestic/Srinagar Tour Package.avif",
  },
];

export default tours;

export const heroData = [
  {
    id: 1,
    title: "Kerala Refined.",
    description:
      "Experience bespoke luxury travel. From private houseboats to mist-covered estates, we curate the soul of Kerala.",
    image: "https://mayaholidays.in/img/carousel-1.jpg",
    badge: "God's Own Country",
    tags: [
      { icon: <Waves size={14} />, label: "Backwaters" },
      { icon: <Star size={14} />, label: "Premium Stay" },
    ],
  },
  {
    id: 2,
    title: "Misty Munnar.",
    description:
      "Walk through blue tea gardens and stay in colonial-style estates overlooking the Western Ghats.",
    image: "/HeroImages/valparai-tour-package.webp",
    badge: "Hill Station Special",
    tags: [
      { icon: <Palmtree size={14} />, label: "Tea Gardens" },
      { icon: <Mountain size={14} />, label: "Trekking" },
    ],
  },
];
